#############################################################################
# Makefile for building: AngryThing.app/Contents/MacOS/AngryThing
# Generated by qmake (3.0) (Qt 5.6.0)
# Project:  AngryThing.pro
# Template: app
# Command: /Users/leonah/Qt5.6.0/5.6/clang_64/bin/qmake -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug -o Makefile AngryThing.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_QML_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -mmacosx-version-min=10.7 -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -g -std=gnu++11 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -mmacosx-version-min=10.7 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -I/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtWidgets.framework/Headers -I/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtGui.framework/Headers -I/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/AGL.framework/Headers -I. -I/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/macx-clang -F/Users/leonah/Qt5.6.0/5.6/clang_64/lib
QMAKE         = /Users/leonah/Qt5.6.0/5.6/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = AngryThing1.0.0
DISTDIR = /jz/Example-code-for-Project-3-master-3/src/.tmp/AngryThing1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -headerpad_max_install_names -stdlib=libc++ -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -mmacosx-version-min=10.7 -Wl,-rpath,/Users/leonah/Qt5.6.0/5.6/clang_64/lib
LIBS          = $(SUBLIBS) -F/Users/leonah/Qt5.6.0/5.6/clang_64/lib -L. -lBox2D -framework QtWidgets -framework QtGui -framework QtCore -framework OpenGL -framework AGL 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = 

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		gameitem.cpp \
		bird.cpp \
		land.cpp \
		block.cpp \
		bird1.cpp \
		bird2.cpp \
		bird3.cpp qrc_res.cpp \
		moc_mainwindow.cpp \
		moc_gameitem.cpp
OBJECTS       = main.o \
		mainwindow.o \
		gameitem.o \
		bird.o \
		land.o \
		block.o \
		bird1.o \
		bird2.o \
		bird3.o \
		qrc_res.o \
		moc_mainwindow.o \
		moc_gameitem.o
DIST          = ../../TaiKu/Taiku/start.jpg \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/features/spec_pre.prf \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/qdevice.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/features/device_config.prf \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/common/unix.conf \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/common/mac.conf \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/common/macx.conf \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/common/sanitize.conf \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/common/gcc-base.conf \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/common/gcc-base-mac.conf \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/common/clang.conf \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/common/clang-mac.conf \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/qconfig.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_core.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_designer.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_gui.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_help.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_labscontrols_private.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_labstemplates_private.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_location.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_network.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_qml.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_quick.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_script.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_sql.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_svg.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_webview.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_xml.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/features/qt_functions.prf \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/features/qt_config.prf \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/macx-clang/qmake.conf \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/features/exclusive_builds.prf \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/features/default_pre.prf \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/features/mac/default_pre.prf \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/features/resolve_config.prf \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/features/default_post.prf \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/features/mac/sdk.prf \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/features/mac/default_post.prf \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/features/mac/objective_c.prf \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/features/qml_debug.prf \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/features/warn_on.prf \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/features/qt.prf \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/features/resources.prf \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/features/moc.prf \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/features/unix/opengl.prf \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/features/uic.prf \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/features/unix/thread.prf \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/features/mac/rez.prf \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/features/testcase_targets.prf \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/features/exceptions.prf \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/features/yacc.prf \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/features/lex.prf \
		AngryThing.pro mainwindow.h \
		Box2D/Collision/Shapes/b2ChainShape.h \
		Box2D/Collision/Shapes/b2CircleShape.h \
		Box2D/Collision/Shapes/b2EdgeShape.h \
		Box2D/Collision/Shapes/b2PolygonShape.h \
		Box2D/Collision/Shapes/b2Shape.h \
		Box2D/Collision/b2BroadPhase.h \
		Box2D/Collision/b2Collision.h \
		Box2D/Collision/b2Distance.h \
		Box2D/Collision/b2DynamicTree.h \
		Box2D/Collision/b2TimeOfImpact.h \
		Box2D/Common/b2BlockAllocator.h \
		Box2D/Common/b2Draw.h \
		Box2D/Common/b2GrowableStack.h \
		Box2D/Common/b2Math.h \
		Box2D/Common/b2Settings.h \
		Box2D/Common/b2StackAllocator.h \
		Box2D/Common/b2Timer.h \
		Box2D/Dynamics/Contacts/b2ChainAndCircleContact.h \
		Box2D/Dynamics/Contacts/b2ChainAndPolygonContact.h \
		Box2D/Dynamics/Contacts/b2CircleContact.h \
		Box2D/Dynamics/Contacts/b2Contact.h \
		Box2D/Dynamics/Contacts/b2ContactSolver.h \
		Box2D/Dynamics/Contacts/b2EdgeAndCircleContact.h \
		Box2D/Dynamics/Contacts/b2EdgeAndPolygonContact.h \
		Box2D/Dynamics/Contacts/b2PolygonAndCircleContact.h \
		Box2D/Dynamics/Contacts/b2PolygonContact.h \
		Box2D/Dynamics/Joints/b2DistanceJoint.h \
		Box2D/Dynamics/Joints/b2FrictionJoint.h \
		Box2D/Dynamics/Joints/b2GearJoint.h \
		Box2D/Dynamics/Joints/b2Joint.h \
		Box2D/Dynamics/Joints/b2MotorJoint.h \
		Box2D/Dynamics/Joints/b2MouseJoint.h \
		Box2D/Dynamics/Joints/b2PrismaticJoint.h \
		Box2D/Dynamics/Joints/b2PulleyJoint.h \
		Box2D/Dynamics/Joints/b2RevoluteJoint.h \
		Box2D/Dynamics/Joints/b2RopeJoint.h \
		Box2D/Dynamics/Joints/b2WeldJoint.h \
		Box2D/Dynamics/Joints/b2WheelJoint.h \
		Box2D/Dynamics/b2Body.h \
		Box2D/Dynamics/b2ContactManager.h \
		Box2D/Dynamics/b2Fixture.h \
		Box2D/Dynamics/b2Island.h \
		Box2D/Dynamics/b2TimeStep.h \
		Box2D/Dynamics/b2World.h \
		Box2D/Dynamics/b2WorldCallbacks.h \
		Box2D/Rope/b2Rope.h \
		Box2D/Box2D.h \
		gameitem.h \
		bird.h \
		land.h \
		block.h \
		bird1.h \
		bird2.h \
		bird3.h main.cpp \
		mainwindow.cpp \
		gameitem.cpp \
		bird.cpp \
		land.cpp \
		block.cpp \
		bird1.cpp \
		bird2.cpp \
		bird3.cpp
QMAKE_TARGET  = AngryThing
DESTDIR       = 
TARGET        = AngryThing.app/Contents/MacOS/AngryThing


first: all
####### Build rules

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	@test -d AngryThing.app/Contents/MacOS/ || mkdir -p AngryThing.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: AngryThing.pro /Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/macx-clang/qmake.conf /Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/features/spec_pre.prf \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/qdevice.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/features/device_config.prf \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/common/unix.conf \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/common/mac.conf \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/common/macx.conf \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/common/sanitize.conf \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/common/gcc-base.conf \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/common/gcc-base-mac.conf \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/common/clang.conf \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/common/clang-mac.conf \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/qconfig.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_core.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_designer.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_gui.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_help.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_labscontrols_private.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_labstemplates_private.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_location.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_network.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_qml.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_quick.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_script.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_sql.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_svg.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_webview.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_xml.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/features/qt_functions.prf \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/features/qt_config.prf \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/macx-clang/qmake.conf \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/features/exclusive_builds.prf \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/features/default_pre.prf \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/features/mac/default_pre.prf \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/features/resolve_config.prf \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/features/default_post.prf \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/features/mac/sdk.prf \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/features/mac/default_post.prf \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/features/mac/objective_c.prf \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/features/qml_debug.prf \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/features/warn_on.prf \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/features/qt.prf \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/features/resources.prf \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/features/moc.prf \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/features/unix/opengl.prf \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/features/uic.prf \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/features/unix/thread.prf \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/features/mac/rez.prf \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/features/testcase_targets.prf \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/features/exceptions.prf \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/features/yacc.prf \
		/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/features/lex.prf \
		AngryThing.pro \
		res.qrc \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtWidgets.framework/QtWidgets.prl \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtGui.framework/QtGui.prl \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug -o Makefile AngryThing.pro
/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/features/spec_pre.prf:
/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/qdevice.pri:
/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/features/device_config.prf:
/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/common/unix.conf:
/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/common/mac.conf:
/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/common/macx.conf:
/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/common/sanitize.conf:
/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/common/gcc-base.conf:
/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/common/gcc-base-mac.conf:
/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/common/clang.conf:
/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/common/clang-mac.conf:
/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/qconfig.pri:
/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3dcore.pri:
/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri:
/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3dinput.pri:
/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri:
/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3dlogic.pri:
/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3dquick.pri:
/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri:
/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri:
/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri:
/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3drender.pri:
/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_3drender_private.pri:
/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_clucene_private.pri:
/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_core.pri:
/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_core_private.pri:
/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_dbus.pri:
/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_designer.pri:
/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_gui.pri:
/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_help.pri:
/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_help_private.pri:
/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_labscontrols_private.pri:
/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_labstemplates_private.pri:
/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_location.pri:
/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_location_private.pri:
/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_macextras.pri:
/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_network.pri:
/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_network_private.pri:
/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_nfc.pri:
/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_opengl.pri:
/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_positioning.pri:
/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_qml.pri:
/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_quick.pri:
/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_script.pri:
/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_script_private.pri:
/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_sensors.pri:
/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_serialbus.pri:
/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri:
/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_serialport.pri:
/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_sql.pri:
/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_svg.pri:
/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_testlib.pri:
/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_uiplugin.pri:
/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_uitools.pri:
/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_webengine.pri:
/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_webengine_private.pri:
/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_webenginecore.pri:
/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_websockets.pri:
/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_webview.pri:
/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_widgets.pri:
/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_xml.pri:
/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/features/qt_functions.prf:
/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/features/qt_config.prf:
/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/macx-clang/qmake.conf:
/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/features/spec_post.prf:
.qmake.stash:
/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/features/exclusive_builds.prf:
/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/features/default_pre.prf:
/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/features/mac/default_pre.prf:
/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/features/resolve_config.prf:
/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/features/default_post.prf:
/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/features/mac/sdk.prf:
/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/features/mac/default_post.prf:
/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/features/mac/objective_c.prf:
/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/features/qml_debug.prf:
/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/features/warn_on.prf:
/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/features/qt.prf:
/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/features/resources.prf:
/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/features/moc.prf:
/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/features/unix/opengl.prf:
/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/features/uic.prf:
/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/features/unix/thread.prf:
/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/features/mac/rez.prf:
/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/features/testcase_targets.prf:
/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/features/exceptions.prf:
/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/features/yacc.prf:
/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/features/lex.prf:
AngryThing.pro:
res.qrc:
/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtWidgets.framework/QtWidgets.prl:
/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtGui.framework/QtGui.prl:
/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug -o Makefile AngryThing.pro

qmake_all: FORCE

AngryThing.app/Contents/PkgInfo: 
	@test -d AngryThing.app/Contents || mkdir -p AngryThing.app/Contents
	@$(DEL_FILE) AngryThing.app/Contents/PkgInfo
	@echo "APPL????" > AngryThing.app/Contents/PkgInfo
AngryThing.app/Contents/Resources/empty.lproj: 
	@test -d AngryThing.app/Contents/Resources || mkdir -p AngryThing.app/Contents/Resources
	@touch AngryThing.app/Contents/Resources/empty.lproj
	
AngryThing.app/Contents/Info.plist: 
	@test -d AngryThing.app/Contents || mkdir -p AngryThing.app/Contents
	@$(DEL_FILE) AngryThing.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@BUNDLEIDENTIFIER@,com.yourcompany.AngryThing,g" -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,AngryThing,g" -e "s,@LIBRARY@,AngryThing,g" -e "s,@TYPEINFO@,????,g" /Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/macx-clang/Info.plist.app >AngryThing.app/Contents/Info.plist

all: Makefile \
		AngryThing.app/Contents/PkgInfo \
		AngryThing.app/Contents/Resources/empty.lproj \
		AngryThing.app/Contents/Info.plist $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents res.qrc $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.h Box2D/Collision/Shapes/b2ChainShape.h Box2D/Collision/Shapes/b2CircleShape.h Box2D/Collision/Shapes/b2EdgeShape.h Box2D/Collision/Shapes/b2PolygonShape.h Box2D/Collision/Shapes/b2Shape.h Box2D/Collision/b2BroadPhase.h Box2D/Collision/b2Collision.h Box2D/Collision/b2Distance.h Box2D/Collision/b2DynamicTree.h Box2D/Collision/b2TimeOfImpact.h Box2D/Common/b2BlockAllocator.h Box2D/Common/b2Draw.h Box2D/Common/b2GrowableStack.h Box2D/Common/b2Math.h Box2D/Common/b2Settings.h Box2D/Common/b2StackAllocator.h Box2D/Common/b2Timer.h Box2D/Dynamics/Contacts/b2ChainAndCircleContact.h Box2D/Dynamics/Contacts/b2ChainAndPolygonContact.h Box2D/Dynamics/Contacts/b2CircleContact.h Box2D/Dynamics/Contacts/b2Contact.h Box2D/Dynamics/Contacts/b2ContactSolver.h Box2D/Dynamics/Contacts/b2EdgeAndCircleContact.h Box2D/Dynamics/Contacts/b2EdgeAndPolygonContact.h Box2D/Dynamics/Contacts/b2PolygonAndCircleContact.h Box2D/Dynamics/Contacts/b2PolygonContact.h Box2D/Dynamics/Joints/b2DistanceJoint.h Box2D/Dynamics/Joints/b2FrictionJoint.h Box2D/Dynamics/Joints/b2GearJoint.h Box2D/Dynamics/Joints/b2Joint.h Box2D/Dynamics/Joints/b2MotorJoint.h Box2D/Dynamics/Joints/b2MouseJoint.h Box2D/Dynamics/Joints/b2PrismaticJoint.h Box2D/Dynamics/Joints/b2PulleyJoint.h Box2D/Dynamics/Joints/b2RevoluteJoint.h Box2D/Dynamics/Joints/b2RopeJoint.h Box2D/Dynamics/Joints/b2WeldJoint.h Box2D/Dynamics/Joints/b2WheelJoint.h Box2D/Dynamics/b2Body.h Box2D/Dynamics/b2ContactManager.h Box2D/Dynamics/b2Fixture.h Box2D/Dynamics/b2Island.h Box2D/Dynamics/b2TimeStep.h Box2D/Dynamics/b2World.h Box2D/Dynamics/b2WorldCallbacks.h Box2D/Rope/b2Rope.h Box2D/Box2D.h gameitem.h bird.h land.h block.h bird1.h bird2.h bird3.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp mainwindow.cpp gameitem.cpp bird.cpp land.cpp block.cpp bird1.cpp bird2.cpp bird3.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r AngryThing.app
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_rcc_make_all: qrc_res.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_res.cpp
qrc_res.cpp: res.qrc \
		image/GROUND.png \
		image/Normal_Bird_1.png \
		image/start.jpg \
		image/exit.jpg \
		image/Rock.png \
		image/pig.png \
		image/yellowbird.png \
		image/bluebird.png \
		image/oh.png
	/Users/leonah/Qt5.6.0/5.6/clang_64/bin/rcc -name res res.qrc -o qrc_res.cpp

compiler_moc_header_make_all: moc_mainwindow.cpp moc_gameitem.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_gameitem.cpp
moc_mainwindow.cpp: /Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtWidgets.framework/Headers/QGraphicsScene \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtWidgets.framework/Headers/qgraphicsscene.h \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtCore.framework/Headers/QList \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtCore.framework/Headers/qlist.h \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtWidgets.framework/Headers/QDesktopWidget \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtWidgets.framework/Headers/qdesktopwidget.h \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtCore.framework/Headers/QTimer \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtCore.framework/Headers/qtimer.h \
		Box2D/Box2D.h \
		Box2D/Common/b2Settings.h \
		Box2D/Common/b2Draw.h \
		Box2D/Common/b2Math.h \
		Box2D/Common/b2Timer.h \
		Box2D/Collision/Shapes/b2CircleShape.h \
		Box2D/Collision/Shapes/b2Shape.h \
		Box2D/Common/b2BlockAllocator.h \
		Box2D/Collision/b2Collision.h \
		Box2D/Collision/Shapes/b2EdgeShape.h \
		Box2D/Collision/Shapes/b2ChainShape.h \
		Box2D/Collision/Shapes/b2PolygonShape.h \
		Box2D/Collision/b2BroadPhase.h \
		Box2D/Collision/b2DynamicTree.h \
		Box2D/Common/b2GrowableStack.h \
		Box2D/Collision/b2Distance.h \
		Box2D/Collision/b2TimeOfImpact.h \
		Box2D/Dynamics/b2Body.h \
		Box2D/Dynamics/b2Fixture.h \
		Box2D/Dynamics/b2WorldCallbacks.h \
		Box2D/Dynamics/b2TimeStep.h \
		Box2D/Dynamics/b2World.h \
		Box2D/Common/b2StackAllocator.h \
		Box2D/Dynamics/b2ContactManager.h \
		Box2D/Dynamics/Contacts/b2Contact.h \
		Box2D/Dynamics/Joints/b2DistanceJoint.h \
		Box2D/Dynamics/Joints/b2Joint.h \
		Box2D/Dynamics/Joints/b2FrictionJoint.h \
		Box2D/Dynamics/Joints/b2GearJoint.h \
		Box2D/Dynamics/Joints/b2MotorJoint.h \
		Box2D/Dynamics/Joints/b2MouseJoint.h \
		Box2D/Dynamics/Joints/b2PrismaticJoint.h \
		Box2D/Dynamics/Joints/b2PulleyJoint.h \
		Box2D/Dynamics/Joints/b2RevoluteJoint.h \
		Box2D/Dynamics/Joints/b2RopeJoint.h \
		Box2D/Dynamics/Joints/b2WeldJoint.h \
		Box2D/Dynamics/Joints/b2WheelJoint.h \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtGui.framework/Headers/QMouseEvent \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtGui.framework/Headers/qevent.h \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtWidgets.framework/Headers/QGraphicsItem \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtWidgets.framework/Headers/qgraphicsitem.h \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtWidgets.framework/Headers/QGraphicsPixmapItem \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtWidgets.framework/Headers/QGraphicsSceneMouseEvent \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtWidgets.framework/Headers/qgraphicssceneevent.h \
		gameitem.h \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtGui.framework/Headers/QPainter \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtGui.framework/Headers/QTransform \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtGui.framework/Headers/qtransform.h \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtCore.framework/Headers/QtMath \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtCore.framework/Headers/qmath.h \
		land.h \
		bird.h \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtGui.framework/Headers/QPixmap \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtGui.framework/Headers/qpixmap.h \
		bird1.h \
		block.h \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtGui.framework/Headers/QKeyEvent \
		mainwindow.h
	/Users/leonah/Qt5.6.0/5.6/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/macx-clang -I/jz/Example-code-for-Project-3-master-3/src -I/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtWidgets.framework/Headers -I/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtGui.framework/Headers -I/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtCore.framework/Headers -F/Users/leonah/Qt5.6.0/5.6/clang_64/lib mainwindow.h -o moc_mainwindow.cpp

moc_gameitem.cpp: Box2D/Box2D.h \
		Box2D/Common/b2Settings.h \
		Box2D/Common/b2Draw.h \
		Box2D/Common/b2Math.h \
		Box2D/Common/b2Timer.h \
		Box2D/Collision/Shapes/b2CircleShape.h \
		Box2D/Collision/Shapes/b2Shape.h \
		Box2D/Common/b2BlockAllocator.h \
		Box2D/Collision/b2Collision.h \
		Box2D/Collision/Shapes/b2EdgeShape.h \
		Box2D/Collision/Shapes/b2ChainShape.h \
		Box2D/Collision/Shapes/b2PolygonShape.h \
		Box2D/Collision/b2BroadPhase.h \
		Box2D/Collision/b2DynamicTree.h \
		Box2D/Common/b2GrowableStack.h \
		Box2D/Collision/b2Distance.h \
		Box2D/Collision/b2TimeOfImpact.h \
		Box2D/Dynamics/b2Body.h \
		Box2D/Dynamics/b2Fixture.h \
		Box2D/Dynamics/b2WorldCallbacks.h \
		Box2D/Dynamics/b2TimeStep.h \
		Box2D/Dynamics/b2World.h \
		Box2D/Common/b2StackAllocator.h \
		Box2D/Dynamics/b2ContactManager.h \
		Box2D/Dynamics/Contacts/b2Contact.h \
		Box2D/Dynamics/Joints/b2DistanceJoint.h \
		Box2D/Dynamics/Joints/b2Joint.h \
		Box2D/Dynamics/Joints/b2FrictionJoint.h \
		Box2D/Dynamics/Joints/b2GearJoint.h \
		Box2D/Dynamics/Joints/b2MotorJoint.h \
		Box2D/Dynamics/Joints/b2MouseJoint.h \
		Box2D/Dynamics/Joints/b2PrismaticJoint.h \
		Box2D/Dynamics/Joints/b2PulleyJoint.h \
		Box2D/Dynamics/Joints/b2RevoluteJoint.h \
		Box2D/Dynamics/Joints/b2RopeJoint.h \
		Box2D/Dynamics/Joints/b2WeldJoint.h \
		Box2D/Dynamics/Joints/b2WheelJoint.h \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtWidgets.framework/Headers/QGraphicsScene \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtWidgets.framework/Headers/qgraphicsscene.h \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtWidgets.framework/Headers/QGraphicsPixmapItem \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtWidgets.framework/Headers/qgraphicsitem.h \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtGui.framework/Headers/QPainter \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtGui.framework/Headers/QTransform \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtGui.framework/Headers/qtransform.h \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtCore.framework/Headers/QtMath \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtCore.framework/Headers/qmath.h \
		gameitem.h
	/Users/leonah/Qt5.6.0/5.6/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/Users/leonah/Qt5.6.0/5.6/clang_64/mkspecs/macx-clang -I/jz/Example-code-for-Project-3-master-3/src -I/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtWidgets.framework/Headers -I/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtGui.framework/Headers -I/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtCore.framework/Headers -F/Users/leonah/Qt5.6.0/5.6/clang_64/lib gameitem.h -o moc_gameitem.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui
	/Users/leonah/Qt5.6.0/5.6/clang_64/bin/uic mainwindow.ui -o ui_mainwindow.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtWidgets.framework/Headers/QGraphicsScene \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtWidgets.framework/Headers/qgraphicsscene.h \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtCore.framework/Headers/QList \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtCore.framework/Headers/qlist.h \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtWidgets.framework/Headers/QDesktopWidget \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtWidgets.framework/Headers/qdesktopwidget.h \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtCore.framework/Headers/QTimer \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtCore.framework/Headers/qtimer.h \
		Box2D/Box2D.h \
		Box2D/Common/b2Settings.h \
		Box2D/Common/b2Draw.h \
		Box2D/Common/b2Math.h \
		Box2D/Common/b2Timer.h \
		Box2D/Collision/Shapes/b2CircleShape.h \
		Box2D/Collision/Shapes/b2Shape.h \
		Box2D/Common/b2BlockAllocator.h \
		Box2D/Collision/b2Collision.h \
		Box2D/Collision/Shapes/b2EdgeShape.h \
		Box2D/Collision/Shapes/b2ChainShape.h \
		Box2D/Collision/Shapes/b2PolygonShape.h \
		Box2D/Collision/b2BroadPhase.h \
		Box2D/Collision/b2DynamicTree.h \
		Box2D/Common/b2GrowableStack.h \
		Box2D/Collision/b2Distance.h \
		Box2D/Collision/b2TimeOfImpact.h \
		Box2D/Dynamics/b2Body.h \
		Box2D/Dynamics/b2Fixture.h \
		Box2D/Dynamics/b2WorldCallbacks.h \
		Box2D/Dynamics/b2TimeStep.h \
		Box2D/Dynamics/b2World.h \
		Box2D/Common/b2StackAllocator.h \
		Box2D/Dynamics/b2ContactManager.h \
		Box2D/Dynamics/Contacts/b2Contact.h \
		Box2D/Dynamics/Joints/b2DistanceJoint.h \
		Box2D/Dynamics/Joints/b2Joint.h \
		Box2D/Dynamics/Joints/b2FrictionJoint.h \
		Box2D/Dynamics/Joints/b2GearJoint.h \
		Box2D/Dynamics/Joints/b2MotorJoint.h \
		Box2D/Dynamics/Joints/b2MouseJoint.h \
		Box2D/Dynamics/Joints/b2PrismaticJoint.h \
		Box2D/Dynamics/Joints/b2PulleyJoint.h \
		Box2D/Dynamics/Joints/b2RevoluteJoint.h \
		Box2D/Dynamics/Joints/b2RopeJoint.h \
		Box2D/Dynamics/Joints/b2WeldJoint.h \
		Box2D/Dynamics/Joints/b2WheelJoint.h \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtGui.framework/Headers/QMouseEvent \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtGui.framework/Headers/qevent.h \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtWidgets.framework/Headers/QGraphicsItem \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtWidgets.framework/Headers/qgraphicsitem.h \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtWidgets.framework/Headers/QGraphicsPixmapItem \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtWidgets.framework/Headers/QGraphicsSceneMouseEvent \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtWidgets.framework/Headers/qgraphicssceneevent.h \
		gameitem.h \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtGui.framework/Headers/QPainter \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtGui.framework/Headers/QTransform \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtGui.framework/Headers/qtransform.h \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtCore.framework/Headers/QtMath \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtCore.framework/Headers/qmath.h \
		land.h \
		bird.h \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtGui.framework/Headers/QPixmap \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtGui.framework/Headers/qpixmap.h \
		bird1.h \
		block.h \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtGui.framework/Headers/QKeyEvent \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtWidgets.framework/Headers/QApplication \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtWidgets.framework/Headers/qapplication.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtWidgets.framework/Headers/QGraphicsScene \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtWidgets.framework/Headers/qgraphicsscene.h \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtCore.framework/Headers/QList \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtCore.framework/Headers/qlist.h \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtWidgets.framework/Headers/QDesktopWidget \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtWidgets.framework/Headers/qdesktopwidget.h \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtCore.framework/Headers/QTimer \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtCore.framework/Headers/qtimer.h \
		Box2D/Box2D.h \
		Box2D/Common/b2Settings.h \
		Box2D/Common/b2Draw.h \
		Box2D/Common/b2Math.h \
		Box2D/Common/b2Timer.h \
		Box2D/Collision/Shapes/b2CircleShape.h \
		Box2D/Collision/Shapes/b2Shape.h \
		Box2D/Common/b2BlockAllocator.h \
		Box2D/Collision/b2Collision.h \
		Box2D/Collision/Shapes/b2EdgeShape.h \
		Box2D/Collision/Shapes/b2ChainShape.h \
		Box2D/Collision/Shapes/b2PolygonShape.h \
		Box2D/Collision/b2BroadPhase.h \
		Box2D/Collision/b2DynamicTree.h \
		Box2D/Common/b2GrowableStack.h \
		Box2D/Collision/b2Distance.h \
		Box2D/Collision/b2TimeOfImpact.h \
		Box2D/Dynamics/b2Body.h \
		Box2D/Dynamics/b2Fixture.h \
		Box2D/Dynamics/b2WorldCallbacks.h \
		Box2D/Dynamics/b2TimeStep.h \
		Box2D/Dynamics/b2World.h \
		Box2D/Common/b2StackAllocator.h \
		Box2D/Dynamics/b2ContactManager.h \
		Box2D/Dynamics/Contacts/b2Contact.h \
		Box2D/Dynamics/Joints/b2DistanceJoint.h \
		Box2D/Dynamics/Joints/b2Joint.h \
		Box2D/Dynamics/Joints/b2FrictionJoint.h \
		Box2D/Dynamics/Joints/b2GearJoint.h \
		Box2D/Dynamics/Joints/b2MotorJoint.h \
		Box2D/Dynamics/Joints/b2MouseJoint.h \
		Box2D/Dynamics/Joints/b2PrismaticJoint.h \
		Box2D/Dynamics/Joints/b2PulleyJoint.h \
		Box2D/Dynamics/Joints/b2RevoluteJoint.h \
		Box2D/Dynamics/Joints/b2RopeJoint.h \
		Box2D/Dynamics/Joints/b2WeldJoint.h \
		Box2D/Dynamics/Joints/b2WheelJoint.h \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtGui.framework/Headers/QMouseEvent \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtGui.framework/Headers/qevent.h \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtWidgets.framework/Headers/QGraphicsItem \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtWidgets.framework/Headers/qgraphicsitem.h \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtWidgets.framework/Headers/QGraphicsPixmapItem \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtWidgets.framework/Headers/QGraphicsSceneMouseEvent \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtWidgets.framework/Headers/qgraphicssceneevent.h \
		gameitem.h \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtGui.framework/Headers/QPainter \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtGui.framework/Headers/QTransform \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtGui.framework/Headers/qtransform.h \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtCore.framework/Headers/QtMath \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtCore.framework/Headers/qmath.h \
		land.h \
		bird.h \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtGui.framework/Headers/QPixmap \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtGui.framework/Headers/qpixmap.h \
		bird1.h \
		block.h \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtGui.framework/Headers/QKeyEvent \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

gameitem.o: gameitem.cpp gameitem.h \
		Box2D/Box2D.h \
		Box2D/Common/b2Settings.h \
		Box2D/Common/b2Draw.h \
		Box2D/Common/b2Math.h \
		Box2D/Common/b2Timer.h \
		Box2D/Collision/Shapes/b2CircleShape.h \
		Box2D/Collision/Shapes/b2Shape.h \
		Box2D/Common/b2BlockAllocator.h \
		Box2D/Collision/b2Collision.h \
		Box2D/Collision/Shapes/b2EdgeShape.h \
		Box2D/Collision/Shapes/b2ChainShape.h \
		Box2D/Collision/Shapes/b2PolygonShape.h \
		Box2D/Collision/b2BroadPhase.h \
		Box2D/Collision/b2DynamicTree.h \
		Box2D/Common/b2GrowableStack.h \
		Box2D/Collision/b2Distance.h \
		Box2D/Collision/b2TimeOfImpact.h \
		Box2D/Dynamics/b2Body.h \
		Box2D/Dynamics/b2Fixture.h \
		Box2D/Dynamics/b2WorldCallbacks.h \
		Box2D/Dynamics/b2TimeStep.h \
		Box2D/Dynamics/b2World.h \
		Box2D/Common/b2StackAllocator.h \
		Box2D/Dynamics/b2ContactManager.h \
		Box2D/Dynamics/Contacts/b2Contact.h \
		Box2D/Dynamics/Joints/b2DistanceJoint.h \
		Box2D/Dynamics/Joints/b2Joint.h \
		Box2D/Dynamics/Joints/b2FrictionJoint.h \
		Box2D/Dynamics/Joints/b2GearJoint.h \
		Box2D/Dynamics/Joints/b2MotorJoint.h \
		Box2D/Dynamics/Joints/b2MouseJoint.h \
		Box2D/Dynamics/Joints/b2PrismaticJoint.h \
		Box2D/Dynamics/Joints/b2PulleyJoint.h \
		Box2D/Dynamics/Joints/b2RevoluteJoint.h \
		Box2D/Dynamics/Joints/b2RopeJoint.h \
		Box2D/Dynamics/Joints/b2WeldJoint.h \
		Box2D/Dynamics/Joints/b2WheelJoint.h \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtWidgets.framework/Headers/QGraphicsScene \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtWidgets.framework/Headers/qgraphicsscene.h \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtWidgets.framework/Headers/QGraphicsPixmapItem \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtWidgets.framework/Headers/qgraphicsitem.h \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtGui.framework/Headers/QPainter \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtGui.framework/Headers/QTransform \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtGui.framework/Headers/qtransform.h \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtCore.framework/Headers/QtMath \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtCore.framework/Headers/qmath.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o gameitem.o gameitem.cpp

bird.o: bird.cpp bird.h \
		gameitem.h \
		Box2D/Box2D.h \
		Box2D/Common/b2Settings.h \
		Box2D/Common/b2Draw.h \
		Box2D/Common/b2Math.h \
		Box2D/Common/b2Timer.h \
		Box2D/Collision/Shapes/b2CircleShape.h \
		Box2D/Collision/Shapes/b2Shape.h \
		Box2D/Common/b2BlockAllocator.h \
		Box2D/Collision/b2Collision.h \
		Box2D/Collision/Shapes/b2EdgeShape.h \
		Box2D/Collision/Shapes/b2ChainShape.h \
		Box2D/Collision/Shapes/b2PolygonShape.h \
		Box2D/Collision/b2BroadPhase.h \
		Box2D/Collision/b2DynamicTree.h \
		Box2D/Common/b2GrowableStack.h \
		Box2D/Collision/b2Distance.h \
		Box2D/Collision/b2TimeOfImpact.h \
		Box2D/Dynamics/b2Body.h \
		Box2D/Dynamics/b2Fixture.h \
		Box2D/Dynamics/b2WorldCallbacks.h \
		Box2D/Dynamics/b2TimeStep.h \
		Box2D/Dynamics/b2World.h \
		Box2D/Common/b2StackAllocator.h \
		Box2D/Dynamics/b2ContactManager.h \
		Box2D/Dynamics/Contacts/b2Contact.h \
		Box2D/Dynamics/Joints/b2DistanceJoint.h \
		Box2D/Dynamics/Joints/b2Joint.h \
		Box2D/Dynamics/Joints/b2FrictionJoint.h \
		Box2D/Dynamics/Joints/b2GearJoint.h \
		Box2D/Dynamics/Joints/b2MotorJoint.h \
		Box2D/Dynamics/Joints/b2MouseJoint.h \
		Box2D/Dynamics/Joints/b2PrismaticJoint.h \
		Box2D/Dynamics/Joints/b2PulleyJoint.h \
		Box2D/Dynamics/Joints/b2RevoluteJoint.h \
		Box2D/Dynamics/Joints/b2RopeJoint.h \
		Box2D/Dynamics/Joints/b2WeldJoint.h \
		Box2D/Dynamics/Joints/b2WheelJoint.h \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtWidgets.framework/Headers/QGraphicsScene \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtWidgets.framework/Headers/qgraphicsscene.h \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtWidgets.framework/Headers/QGraphicsPixmapItem \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtWidgets.framework/Headers/qgraphicsitem.h \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtGui.framework/Headers/QPainter \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtGui.framework/Headers/QTransform \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtGui.framework/Headers/qtransform.h \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtCore.framework/Headers/QtMath \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtCore.framework/Headers/qmath.h \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtGui.framework/Headers/QPixmap \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtGui.framework/Headers/qpixmap.h \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtCore.framework/Headers/QTimer \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtCore.framework/Headers/qtimer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bird.o bird.cpp

land.o: land.cpp land.h \
		gameitem.h \
		Box2D/Box2D.h \
		Box2D/Common/b2Settings.h \
		Box2D/Common/b2Draw.h \
		Box2D/Common/b2Math.h \
		Box2D/Common/b2Timer.h \
		Box2D/Collision/Shapes/b2CircleShape.h \
		Box2D/Collision/Shapes/b2Shape.h \
		Box2D/Common/b2BlockAllocator.h \
		Box2D/Collision/b2Collision.h \
		Box2D/Collision/Shapes/b2EdgeShape.h \
		Box2D/Collision/Shapes/b2ChainShape.h \
		Box2D/Collision/Shapes/b2PolygonShape.h \
		Box2D/Collision/b2BroadPhase.h \
		Box2D/Collision/b2DynamicTree.h \
		Box2D/Common/b2GrowableStack.h \
		Box2D/Collision/b2Distance.h \
		Box2D/Collision/b2TimeOfImpact.h \
		Box2D/Dynamics/b2Body.h \
		Box2D/Dynamics/b2Fixture.h \
		Box2D/Dynamics/b2WorldCallbacks.h \
		Box2D/Dynamics/b2TimeStep.h \
		Box2D/Dynamics/b2World.h \
		Box2D/Common/b2StackAllocator.h \
		Box2D/Dynamics/b2ContactManager.h \
		Box2D/Dynamics/Contacts/b2Contact.h \
		Box2D/Dynamics/Joints/b2DistanceJoint.h \
		Box2D/Dynamics/Joints/b2Joint.h \
		Box2D/Dynamics/Joints/b2FrictionJoint.h \
		Box2D/Dynamics/Joints/b2GearJoint.h \
		Box2D/Dynamics/Joints/b2MotorJoint.h \
		Box2D/Dynamics/Joints/b2MouseJoint.h \
		Box2D/Dynamics/Joints/b2PrismaticJoint.h \
		Box2D/Dynamics/Joints/b2PulleyJoint.h \
		Box2D/Dynamics/Joints/b2RevoluteJoint.h \
		Box2D/Dynamics/Joints/b2RopeJoint.h \
		Box2D/Dynamics/Joints/b2WeldJoint.h \
		Box2D/Dynamics/Joints/b2WheelJoint.h \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtWidgets.framework/Headers/QGraphicsScene \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtWidgets.framework/Headers/qgraphicsscene.h \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtWidgets.framework/Headers/QGraphicsPixmapItem \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtWidgets.framework/Headers/qgraphicsitem.h \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtGui.framework/Headers/QPainter \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtGui.framework/Headers/QTransform \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtGui.framework/Headers/qtransform.h \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtCore.framework/Headers/QtMath \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtCore.framework/Headers/qmath.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o land.o land.cpp

block.o: block.cpp block.h \
		gameitem.h \
		Box2D/Box2D.h \
		Box2D/Common/b2Settings.h \
		Box2D/Common/b2Draw.h \
		Box2D/Common/b2Math.h \
		Box2D/Common/b2Timer.h \
		Box2D/Collision/Shapes/b2CircleShape.h \
		Box2D/Collision/Shapes/b2Shape.h \
		Box2D/Common/b2BlockAllocator.h \
		Box2D/Collision/b2Collision.h \
		Box2D/Collision/Shapes/b2EdgeShape.h \
		Box2D/Collision/Shapes/b2ChainShape.h \
		Box2D/Collision/Shapes/b2PolygonShape.h \
		Box2D/Collision/b2BroadPhase.h \
		Box2D/Collision/b2DynamicTree.h \
		Box2D/Common/b2GrowableStack.h \
		Box2D/Collision/b2Distance.h \
		Box2D/Collision/b2TimeOfImpact.h \
		Box2D/Dynamics/b2Body.h \
		Box2D/Dynamics/b2Fixture.h \
		Box2D/Dynamics/b2WorldCallbacks.h \
		Box2D/Dynamics/b2TimeStep.h \
		Box2D/Dynamics/b2World.h \
		Box2D/Common/b2StackAllocator.h \
		Box2D/Dynamics/b2ContactManager.h \
		Box2D/Dynamics/Contacts/b2Contact.h \
		Box2D/Dynamics/Joints/b2DistanceJoint.h \
		Box2D/Dynamics/Joints/b2Joint.h \
		Box2D/Dynamics/Joints/b2FrictionJoint.h \
		Box2D/Dynamics/Joints/b2GearJoint.h \
		Box2D/Dynamics/Joints/b2MotorJoint.h \
		Box2D/Dynamics/Joints/b2MouseJoint.h \
		Box2D/Dynamics/Joints/b2PrismaticJoint.h \
		Box2D/Dynamics/Joints/b2PulleyJoint.h \
		Box2D/Dynamics/Joints/b2RevoluteJoint.h \
		Box2D/Dynamics/Joints/b2RopeJoint.h \
		Box2D/Dynamics/Joints/b2WeldJoint.h \
		Box2D/Dynamics/Joints/b2WheelJoint.h \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtWidgets.framework/Headers/QGraphicsScene \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtWidgets.framework/Headers/qgraphicsscene.h \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtWidgets.framework/Headers/QGraphicsPixmapItem \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtWidgets.framework/Headers/qgraphicsitem.h \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtGui.framework/Headers/QPainter \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtGui.framework/Headers/QTransform \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtGui.framework/Headers/qtransform.h \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtCore.framework/Headers/QtMath \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtCore.framework/Headers/qmath.h \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtCore.framework/Headers/QTimer \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtCore.framework/Headers/qtimer.h \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtGui.framework/Headers/QPixmap \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtGui.framework/Headers/qpixmap.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o block.o block.cpp

bird1.o: bird1.cpp bird1.h \
		gameitem.h \
		Box2D/Box2D.h \
		Box2D/Common/b2Settings.h \
		Box2D/Common/b2Draw.h \
		Box2D/Common/b2Math.h \
		Box2D/Common/b2Timer.h \
		Box2D/Collision/Shapes/b2CircleShape.h \
		Box2D/Collision/Shapes/b2Shape.h \
		Box2D/Common/b2BlockAllocator.h \
		Box2D/Collision/b2Collision.h \
		Box2D/Collision/Shapes/b2EdgeShape.h \
		Box2D/Collision/Shapes/b2ChainShape.h \
		Box2D/Collision/Shapes/b2PolygonShape.h \
		Box2D/Collision/b2BroadPhase.h \
		Box2D/Collision/b2DynamicTree.h \
		Box2D/Common/b2GrowableStack.h \
		Box2D/Collision/b2Distance.h \
		Box2D/Collision/b2TimeOfImpact.h \
		Box2D/Dynamics/b2Body.h \
		Box2D/Dynamics/b2Fixture.h \
		Box2D/Dynamics/b2WorldCallbacks.h \
		Box2D/Dynamics/b2TimeStep.h \
		Box2D/Dynamics/b2World.h \
		Box2D/Common/b2StackAllocator.h \
		Box2D/Dynamics/b2ContactManager.h \
		Box2D/Dynamics/Contacts/b2Contact.h \
		Box2D/Dynamics/Joints/b2DistanceJoint.h \
		Box2D/Dynamics/Joints/b2Joint.h \
		Box2D/Dynamics/Joints/b2FrictionJoint.h \
		Box2D/Dynamics/Joints/b2GearJoint.h \
		Box2D/Dynamics/Joints/b2MotorJoint.h \
		Box2D/Dynamics/Joints/b2MouseJoint.h \
		Box2D/Dynamics/Joints/b2PrismaticJoint.h \
		Box2D/Dynamics/Joints/b2PulleyJoint.h \
		Box2D/Dynamics/Joints/b2RevoluteJoint.h \
		Box2D/Dynamics/Joints/b2RopeJoint.h \
		Box2D/Dynamics/Joints/b2WeldJoint.h \
		Box2D/Dynamics/Joints/b2WheelJoint.h \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtWidgets.framework/Headers/QGraphicsScene \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtWidgets.framework/Headers/qgraphicsscene.h \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtWidgets.framework/Headers/QGraphicsPixmapItem \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtWidgets.framework/Headers/qgraphicsitem.h \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtGui.framework/Headers/QPainter \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtGui.framework/Headers/QTransform \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtGui.framework/Headers/qtransform.h \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtCore.framework/Headers/QtMath \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtCore.framework/Headers/qmath.h \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtGui.framework/Headers/QPixmap \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtGui.framework/Headers/qpixmap.h \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtCore.framework/Headers/QTimer \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtCore.framework/Headers/qtimer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bird1.o bird1.cpp

bird2.o: bird2.cpp bird2.h \
		gameitem.h \
		Box2D/Box2D.h \
		Box2D/Common/b2Settings.h \
		Box2D/Common/b2Draw.h \
		Box2D/Common/b2Math.h \
		Box2D/Common/b2Timer.h \
		Box2D/Collision/Shapes/b2CircleShape.h \
		Box2D/Collision/Shapes/b2Shape.h \
		Box2D/Common/b2BlockAllocator.h \
		Box2D/Collision/b2Collision.h \
		Box2D/Collision/Shapes/b2EdgeShape.h \
		Box2D/Collision/Shapes/b2ChainShape.h \
		Box2D/Collision/Shapes/b2PolygonShape.h \
		Box2D/Collision/b2BroadPhase.h \
		Box2D/Collision/b2DynamicTree.h \
		Box2D/Common/b2GrowableStack.h \
		Box2D/Collision/b2Distance.h \
		Box2D/Collision/b2TimeOfImpact.h \
		Box2D/Dynamics/b2Body.h \
		Box2D/Dynamics/b2Fixture.h \
		Box2D/Dynamics/b2WorldCallbacks.h \
		Box2D/Dynamics/b2TimeStep.h \
		Box2D/Dynamics/b2World.h \
		Box2D/Common/b2StackAllocator.h \
		Box2D/Dynamics/b2ContactManager.h \
		Box2D/Dynamics/Contacts/b2Contact.h \
		Box2D/Dynamics/Joints/b2DistanceJoint.h \
		Box2D/Dynamics/Joints/b2Joint.h \
		Box2D/Dynamics/Joints/b2FrictionJoint.h \
		Box2D/Dynamics/Joints/b2GearJoint.h \
		Box2D/Dynamics/Joints/b2MotorJoint.h \
		Box2D/Dynamics/Joints/b2MouseJoint.h \
		Box2D/Dynamics/Joints/b2PrismaticJoint.h \
		Box2D/Dynamics/Joints/b2PulleyJoint.h \
		Box2D/Dynamics/Joints/b2RevoluteJoint.h \
		Box2D/Dynamics/Joints/b2RopeJoint.h \
		Box2D/Dynamics/Joints/b2WeldJoint.h \
		Box2D/Dynamics/Joints/b2WheelJoint.h \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtWidgets.framework/Headers/QGraphicsScene \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtWidgets.framework/Headers/qgraphicsscene.h \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtWidgets.framework/Headers/QGraphicsPixmapItem \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtWidgets.framework/Headers/qgraphicsitem.h \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtGui.framework/Headers/QPainter \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtGui.framework/Headers/QTransform \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtGui.framework/Headers/qtransform.h \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtCore.framework/Headers/QtMath \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtCore.framework/Headers/qmath.h \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtGui.framework/Headers/QPixmap \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtGui.framework/Headers/qpixmap.h \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtCore.framework/Headers/QTimer \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtCore.framework/Headers/qtimer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bird2.o bird2.cpp

bird3.o: bird3.cpp bird3.h \
		gameitem.h \
		Box2D/Box2D.h \
		Box2D/Common/b2Settings.h \
		Box2D/Common/b2Draw.h \
		Box2D/Common/b2Math.h \
		Box2D/Common/b2Timer.h \
		Box2D/Collision/Shapes/b2CircleShape.h \
		Box2D/Collision/Shapes/b2Shape.h \
		Box2D/Common/b2BlockAllocator.h \
		Box2D/Collision/b2Collision.h \
		Box2D/Collision/Shapes/b2EdgeShape.h \
		Box2D/Collision/Shapes/b2ChainShape.h \
		Box2D/Collision/Shapes/b2PolygonShape.h \
		Box2D/Collision/b2BroadPhase.h \
		Box2D/Collision/b2DynamicTree.h \
		Box2D/Common/b2GrowableStack.h \
		Box2D/Collision/b2Distance.h \
		Box2D/Collision/b2TimeOfImpact.h \
		Box2D/Dynamics/b2Body.h \
		Box2D/Dynamics/b2Fixture.h \
		Box2D/Dynamics/b2WorldCallbacks.h \
		Box2D/Dynamics/b2TimeStep.h \
		Box2D/Dynamics/b2World.h \
		Box2D/Common/b2StackAllocator.h \
		Box2D/Dynamics/b2ContactManager.h \
		Box2D/Dynamics/Contacts/b2Contact.h \
		Box2D/Dynamics/Joints/b2DistanceJoint.h \
		Box2D/Dynamics/Joints/b2Joint.h \
		Box2D/Dynamics/Joints/b2FrictionJoint.h \
		Box2D/Dynamics/Joints/b2GearJoint.h \
		Box2D/Dynamics/Joints/b2MotorJoint.h \
		Box2D/Dynamics/Joints/b2MouseJoint.h \
		Box2D/Dynamics/Joints/b2PrismaticJoint.h \
		Box2D/Dynamics/Joints/b2PulleyJoint.h \
		Box2D/Dynamics/Joints/b2RevoluteJoint.h \
		Box2D/Dynamics/Joints/b2RopeJoint.h \
		Box2D/Dynamics/Joints/b2WeldJoint.h \
		Box2D/Dynamics/Joints/b2WheelJoint.h \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtWidgets.framework/Headers/QGraphicsScene \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtWidgets.framework/Headers/qgraphicsscene.h \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtWidgets.framework/Headers/QGraphicsPixmapItem \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtWidgets.framework/Headers/qgraphicsitem.h \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtGui.framework/Headers/QPainter \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtGui.framework/Headers/QTransform \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtGui.framework/Headers/qtransform.h \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtCore.framework/Headers/QtMath \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtCore.framework/Headers/qmath.h \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtGui.framework/Headers/QPixmap \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtGui.framework/Headers/qpixmap.h \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtCore.framework/Headers/QTimer \
		/Users/leonah/Qt5.6.0/5.6/clang_64/lib/QtCore.framework/Headers/qtimer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bird3.o bird3.cpp

qrc_res.o: qrc_res.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_res.o qrc_res.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_gameitem.o: moc_gameitem.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_gameitem.o moc_gameitem.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

